import { card, button } from "../components/ui.js";

export function renderReports() {
  return `
    <div class="space-y-4">
      ${card("Reports & Packs", `
        <div class="text-sm text-slate-600">Generate DG weekly pack, monthly performance pack, SLA breach reports, and audit extracts.</div>
        <div class="mt-3 flex flex-wrap gap-2">
          ${button("DG Weekly Pack", "report.generate", "primary", 'data-type="DG_WEEKLY_PACK"')}
          ${button("Monthly Performance Pack", "report.generate", "ghost", 'data-type="MONTHLY_PERFORMANCE"')}
          ${button("SLA Breach Report", "report.generate", "ghost", 'data-type="SLA_BREACH"')}
          ${button("Audit Extract", "report.generate", "ghost", 'data-type="AUDIT_EXTRACT"')}
        </div>
        <div class="mt-3 text-xs text-slate-500" id="report-status">Reports will be generated by backend and returned as a URL or file reference.</div>
      `)}
    </div>
  `;
}
