import { hydrateGovernance, executeOwnedAction } from '../core/governed-actions.js';
import { State } from '../core/state.js';
import { head, esc, safeUrl, toast, confirmAction, badge, mdBack, mdSwitch, resetDetailScroll, statRow, actionPreview} from '../core/ui.js';
import { UIState } from '../core/ui-state.js';
import { ReceiptLedger } from '../core/receipt-ledger.js';
import { OfflineActionQueue } from '../core/offline-action-queue.js';
import { DeepLinkResolver } from '../core/deeplink-resolver.js';
import { requestSync } from '../core/data-loader.js';
import { selectTaskForAcknowledgement, submitAcknowledgement, buildAcknowledgementPayload, validateAcknowledgementPayload, retryQueuedAcknowledgements, exportAcknowledgementReceipts, acknowledgementHealth, findAcknowledgementTask, resolveAcknowledgementActor } from '../core/acknowledgement-service.js';

export async function mount(el){ hydrateGovernance(); render(el); }
function slaCompliance(tasks) { const withDue = tasks.filter(t => t.ack); if (!withDue.length) return null; const onTime = withDue.filter(t => t.acknowledged && (!t.ackedAt || new Date(t.ackedAt).getTime() <= new Date(t.ack + 'T23:59:59').getTime())); return Math.round((onTime.length / withDue.length) * 100); }
function ageDays(t) { const from = t.created || t.start || t.createdAt; if (!from) return null; return Math.max(0, Math.floor((Date.now() - new Date(from).getTime()) / 86400000)); }
function downloadText(filename, text, type='application/json'){ const blob=new Blob([text],{type}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download=filename; a.click(); setTimeout(()=>URL.revokeObjectURL(a.href),1000); }
function copyText(text,label='Text'){ navigator.clipboard?.writeText(text).then(()=>toast(label+' copied','success')).catch(()=>downloadText(label.replace(/\s+/g,'-').toLowerCase()+'.txt',text,'text/plain')); }
async function buildPreview(task, form={}){ try{return await buildAcknowledgementPayload(task,{source:'acknowledgment-preview', form});}catch(e){return {error:e.message};} }
function actorFormHtml(){ const a=resolveAcknowledgementActor(); return `<section class="panel"><div class="eyebrow panel-eyebrow">Acknowledging User</div><div class="grid" data-ack-user-form><label>Name<input name="actorName" value="${esc(a.name)}" required></label><label>Email<input name="actorEmail" type="email" value="${esc(a.email)}" required></label><label>Persona / Role<input name="persona" value="${esc(a.persona)}"></label><label>Department / Unit<input name="department" value="${esc(a.department)}"></label></div><p class="meta">Captured from: ${esc(a.source)}. These values are submitted inside the acknowledgement payload and receipt ledger.</p></section>`; }
function readActorForm(root){ const box=root.querySelector('[data-ack-user-form]'); if(!box) return {}; return Object.fromEntries([...box.querySelectorAll('input,select,textarea')].map(x=>[x.name,x.value])); }
function ackConvergencePanel(){ const ctx=State.get().deepLinkContext||{}, h=acknowledgementHealth(); return `<section class="panel"><h2>Acknowledgement receipts & deep links</h2><div class="action-row"><span>Deep link context</span><b>${esc(ctx.taskId||ctx.referenceId||'None')}</b></div><div class="action-row"><span>Endpoint</span><b>${esc(h.endpoint)} / ${esc(h.operation)}</b></div><div class="action-row"><span>Receipts</span><b>${h.receipts.count}</b></div><div class="action-row"><span>Queued acknowledgements</span><b>${h.queue.count}</b></div><div class="action-row"><span>Latest receipt</span><b>${esc(h.receipts.latest||'—')}</b></div><div class="toolbar"><button class="btn" data-retry-ack>Retry queued acknowledgements</button><button class="btn ghost" data-export-receipts>Export receipts JSON</button><button class="btn ghost" data-export-receipts-csv>Export receipts CSV</button><button class="btn ghost" data-copy-deeplink>Copy deep-link context</button><button class="btn ghost" data-refresh-data>Load latest data</button></div></section>`; }
function findSelected(tasks,u){ const s=State.get(), ctx=s.deepLinkContext||{}; return selectTaskForAcknowledgement(s,u.selected||ctx.taskId||ctx.referenceId||s.selectedId) || tasks[0] || null; }
function taskRows(tasks, sel){ return tasks.map(t=>{ const age=ageDays(t), active=sel&&String(sel.id)===String(t.id); return `<tr class="row-link ${active?'row-active':''}" data-id="${esc(t.id)}"><td><div>${esc(t.title)}</div><div class="meta">${esc(t.referenceId || t.id)}</div></td><td>${age == null ? '—' : badge(age + 'd', !t.acknowledged && age >= 2 ? 'danger' : '')}</td><td>${badge(t.acknowledged ? 'Acknowledged' : 'Pending', t.acknowledged ? 'ok' : '')}</td></tr>`; }).join(''); }
function render(el) {
  const s = State.get(); const tasks = s.tracking || []; const u = UIState.get('acknowledgment', { selected: null, md: 'list' }); const ctx=s.deepLinkContext||{};
  const sel = findSelected(tasks,u); if(sel && (!u.selected || (ctx.taskId && String(u.selected)!==String(sel.id)))) UIState.set('acknowledgment',{selected:sel.id,md:ctx.taskId||ctx.referenceId?'detail':u.md});
  const pending = tasks.filter(t => !t.acknowledged); const acked = tasks.filter(t => t.acknowledged); const sla = slaCompliance(tasks); const missingCtx=(ctx.taskId||ctx.referenceId) && !findAcknowledgementTask(s,ctx.taskId||ctx.referenceId);
  el.innerHTML = `<div class="workspace">${head('Acknowledgment Queue', 'Compliance acknowledgment desk for routed tasks, deep links, receipts and offline retry.')}
    ${statRow([['Pending Acknowledgements', pending.length], ['Acknowledged Tasks', acked.length], ['SLA Compliance', sla == null ? 'N/A' : sla + '%'], ['Total', tasks.length]])}
    ${missingCtx?`<section class="panel"><div class="notify-banner error show"><b>Deep-linked task not loaded</b><p>The link resolved to ${esc(ctx.taskId||ctx.referenceId)}, but the task is not in local state yet. Use Load latest data or Direct lookup from the command tools.</p></div></section>`:''}
    ${ackConvergencePanel()}
    <div class="split" ${mdSwitch(sel?UIState.get('acknowledgment').md:'list')}><div class="panel">${tasks.length ? `<div class="tablewrap dgo-table-wrap"><table class="dgo-table"><thead><tr><th scope="col">Task</th><th scope="col" class="col-narrow">Ageing</th><th scope="col" class="col-narrow">Status</th></tr></thead><tbody>${taskRows(tasks,sel)}</tbody></table></div>` : '<div class="empty"><h2>No tasks</h2><p>Tasks appear here once assignments are created or synchronized.</p><button class="btn" data-refresh-data>Load latest data</button></div>'}</div>
    <div class="detail-col panel-stack">${sel ? detail(sel) : '<section class="panel"><div class="empty"><h2>Select a task</h2><p>Choose a task or open an acknowledgement deep link.</p></div></section>'}</div></div></div>`;
  bind(el, sel);
}
function bind(el, sel){
  el.querySelectorAll('tbody tr').forEach(tr => tr.onclick = () => { UIState.set('acknowledgment', { selected: tr.dataset.id, md: 'detail' }); render(el); resetDetailScroll(el); });
  el.querySelector('[data-md-back]')?.addEventListener('click', () => { UIState.set('acknowledgment', { md: 'list' }); render(el); });
  el.querySelectorAll('[data-refresh-data]').forEach(b=>b.addEventListener('click',async()=>{ b.disabled=true; try{ await requestSync({source:'acknowledgment',mode:'deeplink-refresh'}); toast('Runtime data synchronization requested','success'); render(el); }catch(e){ toast(e.message,'error'); }finally{ b.disabled=false; } }));
  el.querySelector('[data-retry-ack]')?.addEventListener('click',async e=>{ e.currentTarget.disabled=true; try{ const r=await retryQueuedAcknowledgements(); toast(`Acknowledgement retry complete: ${r.ok} sent, ${r.fail} failed`, r.fail?'error':'success'); render(el); }catch(x){ toast(x.message,'error'); }finally{ e.currentTarget.disabled=false; } });
  el.querySelector('[data-export-receipts]')?.addEventListener('click',()=>downloadText('dgo-acknowledgement-receipts.json', exportAcknowledgementReceipts('json')));
  el.querySelector('[data-export-receipts-csv]')?.addEventListener('click',()=>downloadText('dgo-acknowledgement-receipts.csv', exportAcknowledgementReceipts('csv'), 'text/csv'));
  el.querySelector('[data-copy-deeplink]')?.addEventListener('click',()=>copyText(JSON.stringify(State.get().deepLinkContext||{},null,2),'Deep-link context'));
  const ackBtn = el.querySelector('[data-ack]'); if (ackBtn) ackBtn.onclick = async () => {
    const actorForm=readActorForm(el); const preview=await buildPreview(sel, actorForm); const validation=validateAcknowledgementPayload(preview); if(validation.length) return toast(validation.join('; '),'error');
    if (!await confirmAction({ title: 'Confirm Acknowledgment', body: `<p><b>${esc(sel.title)}</b></p><p>${esc(sel.referenceId || sel.id)}</p>${actionPreview(preview)}`, confirmText:'Acknowledge & sync', cancelText:'Cancel' })) return;
    ackBtn.disabled=true;
    try{ const result=await executeOwnedAction('acknowledgment', 'acknowledge', () => submitAcknowledgement(sel,{source:'acknowledgment', form:actorForm}), { ref: sel.referenceId || sel.id, meta:{deeplink:!!State.get().deepLinkContext?.taskId} }); toast(result.status==='queued'?'Acknowledged locally; backend sync queued':'Acknowledgment recorded and synchronized', result.status==='queued'?'error':'success'); render(el); }
    catch(e){ toast(e.message,'error'); }
    finally{ ackBtn.disabled=false; }
  };
  el.querySelector('[data-remind]')?.addEventListener('click', async () => { if (!await confirmAction({ title: 'Send acknowledgment reminder', body: `<p><b>${esc(sel.title)}</b></p><p>Remind ${esc(sel.assignedTo || 'the assignee')} to acknowledge receipt.</p>` })) return; await executeOwnedAction('acknowledgment','remind-assignee',()=>{ const s=State.get(); State.patch({notifications:[{id:crypto.randomUUID(),at:new Date().toISOString(),taskId:sel.id,referenceId:sel.referenceId||'',title:`Acknowledgment reminder: ${sel.title}`,assignedTo:sel.assignedTo||''},...(s.notifications||[])]},{module:'acknowledgment',action:'ack:remind',ref:sel.referenceId||sel.id});},{ref:sel.referenceId||sel.id}); toast('Reminder queued for '+(sel.assignedTo||'assignee'),'success'); render(el); });
  el.querySelector('[data-track]')?.addEventListener('click',()=>{ State.patch({selectedId:sel.id}); location.hash='#/response-tracking'; });
  el.querySelector('[data-respond]')?.addEventListener('click',()=>{ State.patch({selectedId:sel.id,deepLinkContext:{...(State.get().deepLinkContext||{}),taskId:sel.id,mode:'respond'}}); location.hash='#/orchestrator'; });
  el.querySelector('[data-reassign]')?.addEventListener('click',()=>{ State.patch({selectedId:sel.id,deepLinkContext:{...(State.get().deepLinkContext||{}),taskId:sel.id,mode:'reassign'}}); location.hash='#/single-assignment'; });
  el.querySelector('[data-attachments]')?.addEventListener('click',()=>{ const links=[...(Array.isArray(sel.attachments)?sel.attachments:[]), sel.attachmentLink||sel.AttachmentLink].filter(Boolean); if(!links.length) return toast('No attachments found for this task','error'); window.open(safeUrl(typeof links[0]==='string'?links[0]:(links[0].AbsoluteUri||links[0].absoluteUri||links[0].url||''),'about:blank'),'_blank','noopener,noreferrer'); });
  el.querySelector('[data-copy-payload]')?.addEventListener('click',async()=>copyText(JSON.stringify(await buildPreview(sel, readActorForm(el)),null,2),'Acknowledgement payload'));
  el.querySelector('[data-parse-url]')?.addEventListener('click',()=>{ const r=DeepLinkResolver.parse(location.href); toast(r.route?`Current URL resolves to ${r.route}`:'No acknowledgement deeplink in current URL', r.route?'success':'error'); });
}
function detail(t) {
  const age = ageDays(t); const receipts=ReceiptLedger.byRef(t.referenceId||t.id).concat(ReceiptLedger.byRef(t.id)).slice(0,8);
  return `${mdBack('Back to queue')}<section class="panel"><div class="eyebrow panel-eyebrow">Assigned User Guard</div><p class="meta">Only the assigned user may acknowledge. Assigned To: <b>${esc(t.assignedTo||t.AssignedTo||'—')}</b></p></section><section class="panel"><div class="eyebrow panel-eyebrow">Acknowledgment Notice</div><div class="meta">${esc(t.referenceId || t.id)} · ${badge(t.acknowledged ? 'Acknowledged' : 'Pending', t.acknowledged ? 'ok' : '')}${age != null ? ' · ' + badge('Waiting ' + age + 'd', !t.acknowledged && age >= 2 ? 'danger' : '') : ''}</div><h2>${esc(t.title)}</h2><p class="meta">Assigned to: ${esc(t.assignedTo||'Unassigned')} · Acknowledgement due: ${esc(t.ack||'—')}</p><p>Subject: Task acknowledgment required — ${esc(t.title)}</p></section>
    ${actorFormHtml()}<section class="panel"><div class="eyebrow panel-eyebrow">Acknowledgement Notification</div><p class="meta">On successful acknowledgement the backend payload includes an HTML notification object addressed to the assigned user and copied to Registry.</p></section><section class="panel"><div class="eyebrow panel-eyebrow">Receipt Actions</div><div class="form-row">${t.acknowledged ? '<span class="pill ok">Acknowledgment logged</span>' : '<button class="btn" data-ack>Acknowledge Receipt</button><button class="btn ghost" data-remind>Send Reminder</button>'}<button class="btn ghost" data-track>Track History</button><button class="btn ghost" data-respond>Respond</button><button class="btn ghost" data-reassign>ReAssign / Forward</button><button class="btn ghost" data-attachments>Attachments</button><button class="btn ghost" data-copy-payload>Copy Payload</button><button class="btn ghost" data-parse-url>Parse Current URL</button></div></section>
    <section class="panel"><div class="eyebrow panel-eyebrow">Receipt Ledger</div>${receipts.length?receipts.map(r=>`<div class="action-row"><span><b>${esc(r.status)}</b><small>${esc(r.createdAt||r.at||'')} · ${esc(r.receiptId)}</small></span>${badge(r.source||'ack')}</div>`).join(''):'<p class="meta">No receipts for this task yet.</p>'}</section>`;
}
