import { hydrateGovernance, executeOwnedAction } from '../core/governed-actions.js';
import { State } from '../core/state.js';
import { UIState } from '../core/ui-state.js';
import { head, esc, toast, confirmAction, badge, mdBack, mdSwitch, resetDetailScroll, fmtDateTime } from '../core/ui.js';
import { capRows, RenderBudget } from '../core/render-budget.js';
import { CorrespondenceEmailService as Mail } from '../core/correspondence-email-service.js';

export async function mount(el){ hydrateGovernance(); render(el); }
const U=()=>UIState.get('correspondence-email',{tab:'sources',selected:'',md:'list',template:'official-correspondence'});
function tone(x){ return x.status==='sent'?'ok':x.status==='queued'?'warn':x.status==='archived'?'info':''; }
function render(el){
  const s=State.get(), u=U(), sources=Mail.sourceCorrespondences(s), rows=s.correspondenceEmails||[], stats=Mail.stats(s), selected=rows.find(x=>x.id===u.selected)||null;
  el.innerHTML=`<div class="workspace">${head('Correspondence Email Desk','Official outward correspondence emails with branded templates, drafts, dispatch evidence and sent register.')}
  <section class="panel"><div class="eyebrow panel-eyebrow">Official email correspondence register</div><div class="status-strip"><span class="pill">Drafts: ${stats.draft}</span><span class="pill">Queued: ${stats.queued}</span><span class="pill ok">Sent: ${stats.sent}</span><span class="pill">Total: ${stats.total}</span></div><p>This desk is for actual outward correspondences via email. It is not a task-notification center.</p></section>
  <div class="toolbar"><button class="btn ${u.tab==='sources'?'':'ghost'}" data-tab="sources">Source Correspondence</button><button class="btn ${u.tab==='drafts'?'':'ghost'}" data-tab="drafts">Drafts / Outbox</button><button class="btn ${u.tab==='register'?'':'ghost'}" data-tab="register">Sent Register</button><button class="btn ${u.tab==='templates'?'':'ghost'}" data-tab="templates">Templates</button></div>
  ${u.tab==='templates'?templates():u.tab==='register'?register(rows):workspace(s,u,sources,rows,selected)}</div>`;
  bind(el);
}
function templates(){ return `<section class="panel"><h2>Dynamic official templates</h2><div class="dashboard-grid">${Mail.templates().map(t=>`<article class="panel"><div class="eyebrow">${esc(t.category)}</div><h3>${esc(t.label)}</h3><p class="meta">${esc(t.tone)} template for formal outbound correspondence.</p><span class="pill">${(t.required||[]).length} required fields</span><span class="pill ok">Branded HTML</span></article>`).join('')}</div></section>`; }
function register(rows){ const sent=rows.filter(x=>x.status==='sent'); return `<section class="panel"><h2>Sent correspondence email register</h2>${sent.length?`<div class="tablewrap dgo-table-wrap"><table class="dgo-table"><thead><tr><th>Reference</th><th>Subject</th><th>Recipient</th><th>Template</th><th>Sent</th><th>By</th></tr></thead><tbody>${sent.map(x=>`<tr><td>${esc(x.referenceId)}</td><td>${esc(x.subjectLine||x.subject)}</td><td>${esc(x.recipientEmail)}</td><td>${esc(x.templateId)}</td><td>${esc(fmtDateTime(x.sentAt||''))}</td><td>${esc(x.sentBy||'')}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty"><h2>No sent email correspondences yet</h2></div>'}</section>`; }
function workspace(s,u,sources,rows,selected){ const list=u.tab==='sources'?sources:rows.filter(x=>x.status!=='archived'); return `<div class="split" ${mdSwitch(u.md)}><div class="list-col panel">${u.tab==='sources'?sourceList(list):draftList(list,selected)}</div><div class="detail-col panel-stack">${u.tab==='sources'?composer(sources.find(x=>String(x.id)===String(u.selected))||sources[0]||null,u):selected?detail(selected):'<section class="panel"><div class="empty"><h2>Select a correspondence email</h2></div></section>'}</div></div>`; }
function sourceList(list){ return list.length?capRows(list,RenderBudget.listRows).map(r=>`<div class="list-item" data-source="${esc(r.id)}"><div class="meta">${esc(r.kind)} · ${esc(r.referenceId||'N/A')} ${badge(r.classification||'Official')}</div><h4>${esc(r.subject||'Untitled correspondence')}</h4><div class="meta">Recipient seed: ${esc(r.recipientEmail||r.recipientName||'Not set')}</div></div>`).join(''):'<div class="empty"><h2>No correspondence source records</h2><p>Registered correspondence and registry files appear here.</p></div>'; }
function draftList(list,selected){ return list.length?capRows(list,RenderBudget.listRows).map(x=>`<div class="list-item ${selected&&selected.id===x.id?'active':''}" data-draft="${esc(x.id)}"><div class="meta">${badge(x.status,tone(x))} ${esc(x.referenceId||'—')}</div><h4>${esc(x.subjectLine||x.subject)}</h4><div class="meta">To: ${esc(x.recipientEmail||'—')} · ${esc(fmtDateTime(x.updatedAt||x.createdAt||''))}</div></div>`).join(''):'<div class="empty"><h2>No drafts</h2><p>Create a draft from Source Correspondence.</p></div>'; }
function composer(src,u){
  if(!src)return '<section class="panel"><div class="empty"><h2>No correspondence source selected</h2></div></section>';
  const draft={templateId:u.template,sourceId:src.id,sourceKind:src.kind,referenceId:src.referenceId,subject:src.subject,recipientName:src.recipientName,recipientEmail:src.recipientEmail,classification:src.classification,attachmentSummary:(src.attachmentLinks||[]).join('; ')};
  const rendered=Mail.render(draft,src);
  return `${mdBack('Back to source correspondences')}<form class="panel grid" data-compose><input type="hidden" name="sourceId" value="${esc(src.id)}"><input type="hidden" name="sourceKind" value="${esc(src.kind)}"><div class="eyebrow panel-eyebrow wide">Compose outgoing correspondence email</div><label>Template<select name="templateId">${Mail.templateOptions(u.template)}</select></label><label>Reference<input name="referenceId" value="${esc(rendered.ctx.referenceId)}"></label><label class="wide">Subject<input name="subject" value="${esc(rendered.ctx.subject)}" required></label><label>Recipient name<input name="recipientName" value="${esc(rendered.ctx.recipientName)}"></label><label>Recipient email<input name="recipientEmail" type="email" value="${esc(rendered.ctx.recipientEmail)}" required></label><label>CC<input name="cc" placeholder="email1; email2"></label><label>BCC<input name="bcc"></label><label>Classification<select name="classification"><option>Official</option><option>Confidential</option><option>Restricted</option></select></label><label>Priority<select name="priority"><option>normal</option><option>high</option><option>urgent</option><option>low</option></select></label><label>Due / response date<input name="dueDate" type="date"></label><label class="wide">Action required / instruction<input name="actionRequired"></label><label class="wide">Attachment reference(s)<input name="attachmentSummary" value="${esc(rendered.ctx.attachmentSummary)}"></label><label class="wide">Correspondence body<textarea name="body" rows="6" required>${esc(rendered.ctx.body)}</textarea></label><label>Signatory name<input name="signatoryName" value="${esc(rendered.ctx.signatoryName)}"></label><label>Signatory title<input name="signatoryTitle" value="${esc(rendered.ctx.signatoryTitle)}"></label><div class="wide form-row"><button class="btn">Save Official Draft</button></div></form><section class="panel"><details open><summary>Live premium email preview</summary><iframe title="Correspondence email preview" sandbox="" style="width:100%;height:560px;border:1px solid var(--dgo-color-border-default,#ddd);border-radius:14px;background:white" srcdoc="${esc(rendered.html)}"></iframe></details></section>`;
}
function detail(x){ return `${mdBack('Back to outbox')}<section class="panel"><div class="eyebrow panel-eyebrow">Correspondence email record</div><div class="status-strip">${badge(x.status,tone(x))} ${badge(x.classification)} ${badge(x.priority)}</div><h2>${esc(x.subjectLine||x.subject)}</h2><dl class="detail-grid"><dt>Reference</dt><dd>${esc(x.referenceId)}</dd><dt>To</dt><dd>${esc(x.recipientEmail)}</dd><dt>Template</dt><dd>${esc(x.templateId)}</dd><dt>Updated</dt><dd>${esc(fmtDateTime(x.updatedAt||''))}</dd>${x.sentAt?`<dt>Sent</dt><dd>${esc(fmtDateTime(x.sentAt))}</dd>`:''}${x.lastError?`<dt>Error</dt><dd>${esc(x.lastError)}</dd>`:''}</dl><div class="form-row">${x.status!=='sent'?'<button class="btn" data-send>Send Correspondence Email</button>':''}<button class="btn ghost" data-duplicate>Duplicate</button><button class="btn ghost" data-archive>Archive</button></div></section><section class="panel"><details open><summary>Branded preview</summary><iframe title="Correspondence email preview" sandbox="" style="width:100%;height:560px;border:1px solid var(--dgo-color-border-default,#ddd);border-radius:14px;background:white" srcdoc="${esc(x.html)}"></iframe></details></section><section class="panel"><details><summary>Plain text fallback</summary><pre class="preview-box">${esc(x.plain||'')}</pre></details></section>`; }
function bind(el){
  el.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{UIState.set('correspondence-email',{tab:b.dataset.tab,selected:'',md:'list'});render(el)});
  el.querySelectorAll('[data-source]').forEach(b=>b.onclick=()=>{UIState.set('correspondence-email',{selected:b.dataset.source,md:'detail'});render(el);resetDetailScroll(el)});
  el.querySelectorAll('[data-draft]').forEach(b=>b.onclick=()=>{UIState.set('correspondence-email',{selected:b.dataset.draft,md:'detail'});render(el);resetDetailScroll(el)});
  el.querySelector('[data-md-back]')?.addEventListener('click',()=>{UIState.set('correspondence-email',{md:'list'});render(el)});
  const f=el.querySelector('[data-compose]'); if(f){ f.templateId.onchange=()=>{UIState.set('correspondence-email',{template:f.templateId.value});render(el)}; f.onsubmit=async e=>{ e.preventDefault(); const d=Object.fromEntries(new FormData(f)); const src=Mail.sourceCorrespondences().find(x=>String(x.id)===String(d.sourceId)); const errs=Mail.validate(d); if(errs.length)return toast(errs.join('; '),'error'); await executeOwnedAction('correspondence-email','create-correspondence-email-draft',()=>Mail.saveDraft(d,src),{ref:d.referenceId}); toast('Correspondence email draft saved','success'); UIState.set('correspondence-email',{tab:'drafts',selected:'',md:'list'}); render(el); }; }
  el.querySelector('[data-send]')?.addEventListener('click',async()=>{ const row=(State.get().correspondenceEmails||[]).find(x=>x.id===UIState.get('correspondence-email').selected); if(!row)return; if(!await confirmAction({title:'Send official correspondence email',body:`<p><b>${esc(row.subjectLine)}</b></p><p>To: ${esc(row.recipientEmail)}</p><p>This sends an outward correspondence via the configured EMAIL endpoint.</p>`,confirmText:'Send Correspondence Email'}))return; try{ await executeOwnedAction('correspondence-email','send-correspondence-email',()=>Mail.sendDraft(row),{ref:row.referenceId}); toast('Correspondence email sent','success'); }catch(e){ toast('Correspondence email queued for retry: '+e.message,'error'); } render(el); });
  el.querySelector('[data-duplicate]')?.addEventListener('click',async()=>{ const row=(State.get().correspondenceEmails||[]).find(x=>x.id===UIState.get('correspondence-email').selected); if(!row)return; await executeOwnedAction('correspondence-email','duplicate-correspondence-email',()=>Mail.duplicate(row),{ref:row.referenceId}); toast('Draft duplicated','success'); render(el); });
  el.querySelector('[data-archive]')?.addEventListener('click',async()=>{ const row=(State.get().correspondenceEmails||[]).find(x=>x.id===UIState.get('correspondence-email').selected); if(!row)return; if(!await confirmAction({title:'Archive correspondence email',body:`<p>${esc(row.subjectLine)}</p>`}))return; await executeOwnedAction('correspondence-email','archive-correspondence-email',()=>Mail.archive(row),{ref:row.referenceId}); toast('Correspondence email archived','success'); UIState.set('correspondence-email',{selected:'',md:'list'}); render(el); });
}
