export const ActionOwnership = Object.freeze({
  // scan-intake creates correspondence from a counter deposit. It is an ALLOWED INVOKER,
  // not a second owner: one action, one owner, so the audit event and the service stay
  // identical whichever channel a record came in through.
  'create-correspondence': { owner:'correspondence', allowedInvokers:['scan-intake'], service:'Entities.create', audit:'audit:correspondence-created', backend:'DYNAMIC_ACTIONS.optional' },
  'create-brief': { owner:'briefs', service:'Briefs.create', audit:'audit:brief-created', backend:'DYNAMIC_ACTIONS.optional' },
  'submit-brief': { owner:'briefs', service:'Briefs.transition', audit:'audit:brief-submitted', backend:'DYNAMIC_ACTIONS.optional' },
  'decide-brief': { owner:'briefs', service:'Briefs.transition', audit:'audit:brief-decided', backend:'DYNAMIC_ACTIONS.optional' },
  'request-meeting': { owner:'meetings', service:'Meetings.create', audit:'audit:meeting-requested', backend:'DYNAMIC_ACTIONS.optional' },
  'decide-meeting': { owner:'meetings', service:'Meetings.transition', audit:'audit:meeting-decided', backend:'DYNAMIC_ACTIONS.optional' },
  'meeting-actions-to-tasks': { owner:'meetings', service:'Meetings.actionsToTasks', audit:'audit:meeting-actions-converted', backend:'DYNAMIC_ACTIONS.optional' },
  'create-project': { owner:'projects', service:'Projects.create', audit:'audit:project-created', backend:'DYNAMIC_ACTIONS.optional' },
  'update-project': { owner:'projects', service:'Projects.update', audit:'audit:project-updated', backend:'DYNAMIC_ACTIONS.optional' },
  // backend is SCAN_INTAKE, the key core/scan-intake-service.js actually resolves. It read
  // SCAN_UPLOAD, a name that exists nowhere in the endpoint registry, so anyone building a
  // flow from this governance config would have built against a key the client never calls.
  'scan-deposit': { owner:'scan-intake', service:'ScanIntakeService.depositScan', audit:'audit:scan-deposited', backend:'SCAN_INTAKE.required' },
  triage: { owner:'correspondence', service:'Entities.transitionStatus', audit:'audit:triage-completed', backend:'DYNAMIC_ACTIONS.optional' },
  'assign-one': { owner:'single-assignment', service:'Entities.create(task)', audit:'audit:assigned', backend:'SINGLE_ASSIGNMENT' },
  'bulk-assign': { owner:'bulk-assignment', service:'OtpService+Idempotency', audit:'audit:bulk-assignment-submitted', backend:'BULK_ASSIGNMENT' },
  acknowledge: { owner:'acknowledgment', allowedInvokers:['orchestrator'], service:'AcknowledgementService.submit', audit:'audit:acknowledged', backend:'SUBSIDIARY_ACTIONS' },
  'acknowledge-retry': { owner:'acknowledgment', service:'OfflineActionQueue.retryAckQueue', audit:'audit:acknowledgement-retried', backend:'SUBSIDIARY_ACTIONS' },
  'start-work': { owner:'orchestrator', service:'governedTransition', audit:'audit:work-started', backend:'DYNAMIC_ACTIONS.optional' },
  'complete-action': { owner:'orchestrator', service:'governedTransition', audit:'audit:action-complete', backend:'DYNAMIC_ACTIONS.optional' },
  approve: { owner:'approvals', service:'governedTransition', audit:'audit:approved', backend:'DYNAMIC_ACTIONS.optional' },
  'executive-approve': { owner:'executive', service:'governedTransition', audit:'audit:executive-approved', backend:'DYNAMIC_ACTIONS.optional' },
  'send-dispatch': { owner:'dispatch', service:'DispatchService.dispatchOutbound', audit:'audit:dispatch-started', backend:'DISPATCH_OUTBOUND' },
  'archive-reference': { owner:'archive', service:'ArchiveService.archiveReference', audit:'audit:archived', backend:'ARCHIVE_REFERENCE.optional' },
  'generate-report': { owner:'reports', service:'ReportExportService', audit:'audit:report-generated', backend:'none' },
  'run-checks': { owner:'diagnostics', service:'Diagnostics', audit:'audit:diagnostics-run', backend:'none' },
  'create-correspondence-email-draft': { owner:'correspondence-email', service:'CorrespondenceEmailService.saveDraft', audit:'audit:correspondence-email-draft-created', backend:'none' },
  'send-correspondence-email': { owner:'correspondence-email', service:'CorrespondenceEmailService.sendDraft', audit:'audit:correspondence-email-sent', backend:'EMAIL' },
  'duplicate-correspondence-email': { owner:'correspondence-email', service:'CorrespondenceEmailService.duplicate', audit:'audit:correspondence-email-duplicated', backend:'none' },
  'archive-correspondence-email': { owner:'correspondence-email', service:'CorrespondenceEmailService.archive', audit:'audit:correspondence-email-archived', backend:'none' },
  'profile': { owner:'settings', service:'State.patch', audit:'audit:settings-updated', backend:'none' },
  'create-user': { owner:'user-admin', service:'State.patch', audit:'audit:user-created', backend:'DYNAMIC_ACTIONS.optional' },
  'update-user': { owner:'user-admin', service:'State.patch', audit:'audit:user-updated', backend:'DYNAMIC_ACTIONS.optional' },
  'disable-user': { owner:'user-admin', service:'State.patch', audit:'audit:user-disabled', backend:'DYNAMIC_ACTIONS.optional' },
  'assign-role': { owner:'user-admin', service:'State.patch', audit:'audit:user-role-assigned', backend:'DYNAMIC_ACTIONS.optional' },
  'create-approval': { owner:'approvals', service:'State.patch', audit:'audit:approval-requested', backend:'DYNAMIC_ACTIONS.optional' },
  reject: { owner:'approvals', service:'governedTransition', audit:'audit:rejected', backend:'DYNAMIC_ACTIONS.optional' },
  'executive-return': { owner:'executive', service:'governedTransition', audit:'audit:executive-returned', backend:'DYNAMIC_ACTIONS.optional' },
  'executive-escalate': { owner:'executive', service:'governedTransition', audit:'audit:executive-escalated', backend:'DYNAMIC_ACTIONS.optional' },
  'append-minute': { owner:'executive', service:'State.patch', audit:'audit:executive-minute', backend:'DYNAMIC_ACTIONS.optional' },
  'route-task': { owner:'single-assignment', allowedInvokers:['executive'], service:'createTask', audit:'audit:task-routed', backend:'SINGLE_ASSIGNMENT' },
  'add-comment': { owner:'comments', service:'State.patch', audit:'audit:comment-added', backend:'DYNAMIC_ACTIONS.optional' },
  'remind-assignee': { owner:'acknowledgment', service:'State.patch', audit:'audit:ack-reminder', backend:'DYNAMIC_ACTIONS.optional' },
  'register-file': { owner:'registry', service:'createRegistryFile', audit:'audit:file-registered', backend:'DYNAMIC_ACTIONS.optional' },
  'route-file': { owner:'registry', service:'createMovement', audit:'audit:file-routed', backend:'DYNAMIC_ACTIONS.optional' },
  'receive-file': { owner:'registry', service:'State.patch', audit:'audit:custody-received', backend:'DYNAMIC_ACTIONS.optional' },
  'close-file': { owner:'registry', service:'State.patch', audit:'audit:file-closed', backend:'DYNAMIC_ACTIONS.optional' },
  'archive-file': { owner:'archive', allowedInvokers:['registry'], service:'ArchiveService.archiveReference', audit:'audit:file-archived', backend:'ARCHIVE_REFERENCE.optional' },
  'update-operation': { owner:'activities', service:'updateTaskState', audit:'audit:operation-updated', backend:'DYNAMIC_ACTIONS.optional' },
  'set-reminder': { owner:'orchestrator', service:'State.patch', audit:'audit:reminder-set', backend:'DYNAMIC_ACTIONS' },
  'no-dispatch': { owner:'dispatch', service:'State.patch', audit:'audit:no-dispatch', backend:'none' },
  'retry-dispatch': { owner:'dispatch', service:'WriteManager.backend', audit:'audit:dispatch-retried', backend:'DYNAMIC_ACTIONS' },
  'close-dispatch': { owner:'dispatch', service:'State.patch', audit:'audit:dispatch-closed', backend:'DYNAMIC_ACTIONS.optional' },
  'flag-document': { owner:'activities', allowedInvokers:['lookup'], service:'State.patch', audit:'audit:document-flagged', backend:'DYNAMIC_ACTIONS.optional' },
  'update-task': { owner:'orchestrator', allowedInvokers:['lookup'], service:'updateTaskState', audit:'audit:task-updated', backend:'DYNAMIC_ACTIONS.optional' },
  'create-task-from-email': { owner:'single-assignment', allowedInvokers:['lookup','correspondence'], service:'createTask', audit:'audit:email-task-created', backend:'EMAIL_RELATED_TASK' },
  'convert-email': { owner:'correspondence', service:'Entities.create', audit:'audit:email-converted', backend:'DYNAMIC_ACTIONS.optional' },
  'request-otp': { owner:'bulk-assignment', service:'OtpService.requestOtp', audit:'audit:otp-requested', backend:'OTP_GENERATE' },
  'verify-otp': { owner:'bulk-assignment', service:'OtpService.verifyOtp', audit:'audit:otp-verified', backend:'OTP_VERIFY' },
  'resolve-escalation': { owner:'fasttrack', service:'State.patch', audit:'audit:escalation-resolved', backend:'DYNAMIC_ACTIONS.optional' },
  // Canvas Activities parity lifecycle. All three write one DGOFASTTRACK queue record through
  // WriteManager.backend (idempotency key applied there) and then patch the source activity
  // with the Canvas DGO DIGITAL OPS semantics. They reuse the already-registered
  // DYNAMIC_ACTIONS contract; no new endpoint is introduced.
  'activity-archive': { owner:'activities', service:'ActivityParity.planLifecycleAction+ActivityParity.commitLifecycleAction+WriteManager.backend', audit:'audit:activity-archived', backend:'DYNAMIC_ACTIONS' },
  'activity-siwes': { owner:'activities', service:'ActivityParity.planLifecycleAction+ActivityParity.commitLifecycleAction+WriteManager.backend', audit:'audit:activity-siwes-routed', backend:'DYNAMIC_ACTIONS' },
  'activity-nysc': { owner:'activities', service:'ActivityParity.planLifecycleAction+ActivityParity.commitLifecycleAction+WriteManager.backend', audit:'audit:activity-nysc-routed', backend:'DYNAMIC_ACTIONS' },
  'import-state': { owner:'settings', service:'DataReconciler.apply', audit:'audit:state-imported', backend:'none' }
});
export function actionSpec(action){ return ActionOwnership[action] || null; }
export function actionOwner(action){ return actionSpec(action)?.owner || ''; }
