#!/usr/bin/env node
// Point both applications at the local development server.
//
// Writes the two git-ignored config files the apps already look for. Nothing else in the
// repository changes — running against the dev server and running against Power Automate
// differ only by the contents of these two files, which is the property worth keeping.
//
// Idempotent, and it will not overwrite a config it did not write: a real config.local.js
// holding rotated endpoint URLs is exactly the file you least want a setup script to
// clobber, so it is left alone and reported.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { EndpointKeys } from '../config/endpoints.config.js';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

/* Origin-relative by default.
 *
 * An absolute `http://127.0.0.1:8080` looks harmless and is not: a browser that reached the
 * page as `localhost:8080` then treats every API call as cross-origin and CORS blocks the
 * lot, for no reason other than which spelling of loopback was typed. A path works from
 * whichever hostname the page was opened with, and the dev server hosts both apps itself,
 * so the API is always same-origin. DGO_DEV_BASE overrides it for a split setup. */
const BASE = process.env.DGO_DEV_BASE || '';
const API = `${BASE}/api`;
const DISPLAY = BASE || 'the origin the page is served from';

const MARKER = 'GENERATED BY scripts/dev-setup.mjs';
const force = process.argv.includes('--force');
/* `npm run dev` chains this into the server, so the "now start it" hint would be telling
   you to run the command you are already running. */
const starting = process.argv.includes('--starting');

function writeGenerated(file, contents, label) {
  const rel = path.relative(ROOT, file);
  if (fs.existsSync(file)) {
    const existing = fs.readFileSync(file, 'utf8');
    if (!existing.includes(MARKER) && !force) {
      console.log(`  · ${rel} — left alone (not generated by this script; pass --force to replace)`);
      return false;
    }
    if (existing === contents) {
      console.log(`  · ${rel} — already current`);
      return true;
    }
  }
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, contents);
  console.log(`  ✓ ${rel} — ${label}`);
  return true;
}

// One URL per contract key. The dev server dispatches on the action in the body, but
// giving each key its own path keeps the network panel readable and matches the shape a
// real deployment has.
const endpoints = EndpointKeys.reduce((acc, key) => {
  acc[key] = `${API}/dgo/${key}`;
  return acc;
}, {});

const appConfig = `/* ${MARKER} — do not edit by hand.
 *
 * Points the operations platform at the local development server. Delete this file, or run
 * \`npm run setup:dev -- --force\` after editing, to go back to a different backend.
 *
 * This file is git-ignored. It holds no credential: the dev server has none to hold.
 *
 * Assigned only when nothing has set DGO_CONFIG already, so a harness that injects its own
 * configuration before this script runs — the Playwright suite does exactly that — keeps
 * the configuration it injected instead of having it silently replaced.
 */
window.DGO_CONFIG = window.DGO_CONFIG || {
  endpoints: ${JSON.stringify(endpoints, null, 4).replace(/\n/g, '\n  ')},

  auth: {
    /* Left FALSE deliberately.
     *
     * Turning it on makes the client acquire an Entra token and send a bearer header, and
     * the dev server has no tenant to validate one against — so the app would sit at a
     * sign-in it cannot complete. Local development runs in the same development posture
     * the platform ships with: local profile, advisory RBAC, no token.
     *
     * Nothing here is enforced. See docs/deployment/LOCAL-DEV.md.
     */
    enabled: false,

    /* Set even though auth is off, because two byte paths address the proxy directly by
     * base URL rather than through the endpoint registry: the registry scan deposit
     * (core/scan-intake-service.js) and, on the portal side, intake. Without this,
     * Scan Intake reports itself unconfigured and the module cannot be exercised. */
    proxyBaseUrl: '${API}',
  },
};
`;

const portalConfig = `/* ${MARKER} — do not edit by hand.
 *
 * Points the document portal at the local development server. Empty would put the portal
 * in demo mode, where nothing is transmitted; this makes submissions land in the same
 * store the operations platform reads, so a letter submitted here shows up in the registry.
 *
 * This file is git-ignored and holds no credential.
 *
 * Assigned only when nothing has set PF_CONFIG already — see the note in
 * config/config.local.js for why that matters.
 */
window.PF_CONFIG = window.PF_CONFIG || {
  proxyBaseUrl: '${API}'
};
`;

console.log(`\nWiring both applications to the local dev server — API at ${API}, on ${DISPLAY}.\n`);
writeGenerated(path.join(ROOT, 'config', 'config.local.js'), appConfig,
  `${EndpointKeys.length} endpoints + scan path`);
writeGenerated(path.join(ROOT, 'document-portal', 'config.local.js'), portalConfig,
  'intake, upload, support, status and verification');

// The portal loads config.local.js only if the page references it. Report the truth rather
// than assume, because a silently-ignored config is a confusing failure.
const portalIndex = path.join(ROOT, 'document-portal', 'index.html');
if (fs.existsSync(portalIndex) && !fs.readFileSync(portalIndex, 'utf8').includes('config.local.js')) {
  console.log('\n  ! document-portal/index.html does not load config.local.js — the portal will stay in demo mode.');
}

if (!starting) console.log(`\nNext: npm run dev\n`);
