#!/usr/bin/env node
/**
 * One-command local setup.
 *
 *   npm run setup
 *
 * Recovers the pilot Power Automate endpoints from the archived operations manifest
 * inside ECM_DOCS_DEV.zip and writes the two git-ignored config.local.js files the
 * platform expects. Nothing is committed — both targets are in .gitignore.
 *
 * Idempotent. Never overwrites an existing config.local.js unless --force is passed,
 * so a hand-edited file is safe.
 *
 * These are PILOT credentials for a development environment, recovered from this
 * private repository's own archive. They are not production endpoints. When they are
 * rotated, re-run with --force or edit config/config.local.js directly.
 */

import fs from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const FORCE = process.argv.includes('--force');
const ARCHIVE = path.join(ROOT, 'ECM_DOCS_DEV.zip');
const MANIFEST = 'DGO_Targets_References/NITDA_operations_manifest_ai_ready_UNREDACTED-1.json';

const ok = s => console.log(`  ✅ ${s}`);
const info = s => console.log(`  ·  ${s}`);
const warn = s => console.log(`  ⚠️  ${s}`);

/**
 * Endpoint id → the platform's contract keys.
 *
 * E05, E08 and E10 are the SAME Power Automate workflow (6b3bad30…) reached with
 * different `action` values — that flow backs every governed write, so it fills all the
 * write-side contracts. E09 (Send Email) was never configured in the pilot.
 */
const MAP = {
  E01: ['REFERENCE_DATA'],
  E02: ['GET_DOCS', 'FETCH_EMAIL_ATTACHMENTS'],
  E03: ['FETCH_ALL', 'FETCH_ACTIVITIES'],
  E04: ['EMAIL_RELATED_TASK'],
  E05: ['SINGLE_ASSIGNMENT', 'DYNAMIC_ACTIONS', 'SUBSIDIARY_ACTIONS'],
  E06: ['BULK_ASSIGNMENT_DIRECT'],
  E07: ['BULK_ASSIGNMENT'],
};

function readManifest() {
  if (!fs.existsSync(ARCHIVE)) throw new Error(`Archive not found: ${ARCHIVE}`);
  const raw = execFileSync('unzip', ['-p', ARCHIVE, MANIFEST], { maxBuffer: 64 * 1024 * 1024 });
  return JSON.parse(raw.toString('utf8'));
}

function buildEndpoints(manifest) {
  const byId = {};
  for (const e of manifest.endpoint_registry || []) {
    if (e.full_url && e.configured) byId[e.id] = e.full_url;
  }
  const endpoints = {};
  const provenance = [];
  for (const [id, keys] of Object.entries(MAP)) {
    const url = byId[id];
    if (!url) { provenance.push([id, keys.join(', '), 'not in manifest']); continue; }
    for (const k of keys) endpoints[k] = url;
    provenance.push([id, keys.join(', '), 'recovered']);
  }
  return { endpoints, provenance };
}

function writeIfAbsent(file, contents, label) {
  const abs = path.join(ROOT, file);
  if (fs.existsSync(abs) && !FORCE) { info(`${label} already exists — left untouched (use --force to replace)`); return false; }
  fs.mkdirSync(path.dirname(abs), { recursive: true });
  fs.writeFileSync(abs, contents);
  ok(`${label} written → ${file}`);
  return true;
}

console.log('\nDGO Digital Operations — local setup\n');

let manifest;
try { manifest = readManifest(); }
catch (e) {
  warn(`Could not read the archived manifest: ${e.message}`);
  warn('Falling back to placeholders — copy config/config.example.js and fill it in yourself.');
  process.exit(1);
}

const { endpoints, provenance } = buildEndpoints(manifest);

console.log('  Endpoints recovered from the archived pilot manifest:');
for (const [id, keys, status] of provenance) {
  console.log(`    ${status === 'recovered' ? '✅' : '⚠️ '} ${id}  →  ${keys}${status === 'recovered' ? '' : `  (${status})`}`);
}
console.log('');

const { EndpointKeys } = await import('../config/endpoints.config.js');
const unset = EndpointKeys.filter(k => !endpoints[k]);

const rootCfg = `// GENERATED by "npm run setup" — git-ignored, never committed.
//
// Pilot Power Automate endpoints recovered from the archived operations manifest in
// ECM_DOCS_DEV.zip. These are DEVELOPMENT/PILOT credentials, not production endpoints.
//
// ${unset.length} contract(s) have no pilot endpoint and are intentionally left unset:
//   ${unset.join(', ') || '(none)'}
// Those calls fail gracefully — Diagnostics reports them as unconfigured.
//
// Regenerate after rotation:  npm run setup -- --force

window.DGO_CONFIG = {
  endpoints: ${JSON.stringify(endpoints, null, 4).replace(/\n/g, '\n  ')},

  // Authentication stays INERT for local testing: no sign-in, no token, identity comes
  // from the local profile exactly as it does today. Set enabled:true only once the
  // proxy is deployed and an Entra app is registered — see AUTHENTICATION_CONTRACT.md.
  auth: { enabled: false }
};
`;

const portalCfg = `// GENERATED by "npm run setup" — git-ignored, never committed.
// The ECM Activity Hub Portal talks to a single gateway URL.
window.DGO_CONFIG = Object.assign(window.DGO_CONFIG || {}, {
  API_URL: ${JSON.stringify(endpoints.SUBSIDIARY_ACTIONS || endpoints.DYNAMIC_ACTIONS || '')},
  devIdentity: { email: 'operator@localhost', name: 'Development Operator', role: 'Officer' }
});
`;

writeIfAbsent('config/config.local.js', rootCfg, 'Root runtime config');
writeIfAbsent('ECM_ActivityHub_Portal/config.local.js', portalCfg, 'ECM Portal config');

console.log(`\n  ${Object.keys(endpoints).length} of ${EndpointKeys.length} endpoint contracts configured.`);
if (unset.length) console.log(`  Unset (no pilot endpoint exists): ${unset.join(', ')}`);

console.log(`
  Ready. Start everything with:

     npm start

  Then open:
     Root runtime    http://localhost:8080/
     ECM Portal      http://localhost:8080/ECM_ActivityHub_Portal/
     Document Portal http://localhost:8080/document-portal/

  Check wiring at  http://localhost:8080/#/diagnostics  (URLs are redacted there).
`);
